name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: "windows-latest"

    steps:
      - name: Install Coq
        run: choco install -y coq