name: CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: "windows-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      # See https://github.com/ocaml-opam/opam-repository-mingw#updates for `opam-repositories`.
      - name: Install OCaml
        uses: ocaml/setup-ocaml@42bf33a4dd3ba5d75a4c9ea6b27d960c9eb4a018 # v2.2.8
        with:
          ocaml-compiler: "4.14.1"
          opam-repositories: |
            opam-repository-mingw: https://github.com/ocaml-opam/opam-repository-mingw.git#sunset
            default: https://github.com/ocaml/opam-repository.git
          dune-cache: true

      - name: Try Coqfmt
        run: git clone https://github.com/toku-sa-n/coqfmt.git

      - name: Install Coqfmt
        run: |
          cd coqfmt
          opam install . --deps-only
          opam install .
